version: '3.7'
services:
  golang:
    environment:
      MIRROR_SOURCE: aliyun
    image: app/golang:1.12
    container_name: app_golang
    build:
      context: .
      dockerfile: ./services/go/Dockerfile
    ports:
      - "1314:1313"
    volumes:
      - ${HOME}/app:/app:rw
      - ./services/go/bin:/go/bin:rw
      - ./services/go/pkg:/go/pkg:rw
    stdin_open: true
    tty: true
    restart: always
    networks:
      - app

networks:
  app:
    name: app # `docker network ls` 查询 && 根据实际填写