version: '3.7'
services:

  mysql:
    environment:
      MIRROR_SOURCE: aliyun    
    image: app/mysql:5.7
    container_name: app_mysql
    build:
      context: .
      dockerfile: ./services/mysql/Dockerfile    
    ports:
      - "3306:3306"
    volumes:
      - ./services/mysql/data:/var/lib/mysql:rw
      - ./services/mysql/etc:/etc/mysql:ro # 自定义配置文件
      - ./services/mysql/log:/var/log/mysql:rw
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    restart: always
    command: "--character-set-server=utf8"
    networks:
      - common    

  redis:
    environment:
      MIRROR_SOURCE: aliyun    
    image: app/redis:3.2
    container_name: app_redis
    build:
      context: .
      dockerfile: ./services/redis/Dockerfile        
    ports:
      - "6379:6379"
    volumes:
      - ${HOME}/app:/app:rw
    restart: always
    networks:
      - common    

  postgres:
    image: app/postgres:10
    container_name: app_postgres
    restart: always
    environment:
      MIRROR_SOURCE: aliyun  
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    build:
      context: .
      dockerfile: ./services/postgres/Dockerfile
    volumes:
      - ./services/postgres/data:/var/lib/postgresql/data:rw
      - ${HOME}/app:/app:rw
    networks:
      - common

networks:
  common: # 公用网络
    name: dockerfiles_default # `docker network ls` 查询 && 根据实际填写