version: '3.7'
services:

  postgres:
    image: app/postgres:10
    container_name: app_postgres
    restart: always
    environment:
      MIRROR_SOURCE: aliyun  
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    build:
      context: .
      dockerfile: ./services/postgres/Dockerfile
    volumes:
      - ./services/postgres/data:/var/lib/postgresql/data:rw
      - ${HOME}/app:/app:rw
    networks:
      - app

networks:
  app:
    name: app # `docker network ls` 查询 && 根据实际填写