version: '3.7'
services:
  tomcat:
    image: app/tomcat:8-jre8
    container_name: app_tomcat
    build:
      context: .
      dockerfile: ./services/tomcat/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./services/tomcat/logs:/usr/local/tomcat/logs
      # - ./services/tomcat/webapps:/usr/local/tomcat/webapps
    networks:
      - app

networks:
  app:
    name: app # `docker network ls` 查询 && 根据实际填写